import matplotlib.pyplot as plt
import numpy as np
plt.tick_params(labelsize=20)
error_DBN = np.load('./result/error_DBN.npy')
error_SSDBN = np.load('./result/error_SSDBN.npy')
tr_normal_sigmoid = np.load('./result/tr_normal_sigmoid.npy')
te_normal_sigmoid = np.load('./result/te_normal_sigmoid.npy')
tr_DBN_sigmoid = np.load('./result/tr_DBN_sigmoid.npy')
te_DBN_sigmoid = np.load('./result/te_DBN_sigmoid.npy')
tr_SSDBN_sigmoid_01 = np.load('./result/tr_SSDBN_sigmoid_0.1.npy')
te_SSDBN_sigmoid_01 = np.load('./result/te_SSDBN_sigmoid_0.1.npy')
tr_SSDBN_sigmoid_03 = np.load('./result/tr_SSDBN_sigmoid_0.3.npy')
te_SSDBN_sigmoid_03 = np.load('./result/te_SSDBN_sigmoid_0.3.npy')
tr_SSDBN_sigmoid_05 = np.load('./result/tr_SSDBN_sigmoid_0.5.npy')
te_SSDBN_sigmoid_05 = np.load('./result/te_SSDBN_sigmoid_0.5.npy')
tr_SSDBN_sigmoid_1 = np.load('./result/tr_SSDBN_sigmoid_1.npy')
te_SSDBN_sigmoid_1 = np.load('./result/te_SSDBN_sigmoid_1.npy')
tr_SSDBN_sigmoid_15 = np.load('./result/tr_SSDBN_sigmoid_1.5.npy')
te_SSDBN_sigmoid_15 = np.load('./result/te_SSDBN_sigmoid_1.5.npy')
tr_SSDBN_sigmoid_2 = np.load('./result/tr_SSDBN_sigmoid_2.npy')
te_SSDBN_sigmoid_2 = np.load('./result/te_SSDBN_sigmoid_2.npy')
tr_DBN_isigmoid_7_001 = np.load('./result/tr_DBN_isigmoid_7_0.01.npy')
te_DBN_isigmoid_7_001 = np.load('./result/te_DBN_isigmoid_7_0.01.npy')
tr_DBN_isigmoid_7_005 = np.load('./result/tr_DBN_isigmoid_7_0.05.npy')
te_DBN_isigmoid_7_005 = np.load('./result/te_DBN_isigmoid_7_0.05.npy')
tr_DBN_isigmoid_7_01 = np.load('./result/tr_DBN_isigmoid_7_0.1.npy')
te_DBN_isigmoid_7_01 = np.load('./result/te_DBN_isigmoid_7_0.1.npy')
tr_DBN_isigmoid_7_015 = np.load('./result/tr_DBN_isigmoid_7_0.15.npy')
te_DBN_isigmoid_7_015 = np.load('./result/te_DBN_isigmoid_7_0.15.npy')
tr_DBN_isigmoid_7_02 = np.load('./result/tr_DBN_isigmoid_7_0.2.npy')
te_DBN_isigmoid_7_02 = np.load('./result/te_DBN_isigmoid_7_0.2.npy')
tr_DBN_isigmoid_3_02 = np.load('./result/tr_DBN_isigmoid_3_0.2.npy')
te_DBN_isigmoid_3_02 = np.load('./result/te_DBN_isigmoid_3_0.2.npy')
tr_DBN_isigmoid_4_02 = np.load('./result/tr_DBN_isigmoid_4_0.2.npy')
te_DBN_isigmoid_4_02 = np.load('./result/te_DBN_isigmoid_4_0.2.npy')
tr_DBN_isigmoid_5_02 = np.load('./result/tr_DBN_isigmoid_5_0.2.npy')
te_DBN_isigmoid_5_02 = np.load('./result/te_DBN_isigmoid_5_0.2.npy')
tr_DBN_isigmoid_6_02 = np.load('./result/tr_DBN_isigmoid_6_0.2.npy')
te_DBN_isigmoid_6_02 = np.load('./result/te_DBN_isigmoid_6_0.2.npy')
tr_SSDBN_isigmoid_1_5_02 = np.load('./result/tr_SSDBN_isigmoid_1_5_0.2.npy')
te_SSDBN_isigmoid_1_5_02 = np.load('./result/te_SSDBN_isigmoid_1_5_0.2.npy')
#'''
label = ['SSDBN (Training, Sigmoid)', 'SSDBN (Testing, Sigmoid)', 'SSDBN (Training, Isigmoid)', 'SSDBN (Testing, Isigmoid)']
plt.plot(range(0, 1000, 10), tr_SSDBN_sigmoid_1[0:1000:10], color='r')
plt.plot(range(0, 1000, 10), te_SSDBN_sigmoid_1[0:1000:10], color='r', marker='x')
plt.plot(range(0, 1000, 10), tr_SSDBN_isigmoid_1_5_02[0:1000:10], color='k')
plt.plot(range(0, 1000, 10), te_SSDBN_isigmoid_1_5_02[0:1000:10], color='k', marker='x')
plt.legend(label)
leg = plt.gca().get_legend()
ltext = leg.get_texts()
plt.setp(ltext, fontsize=20)
plt.xlabel('Epoch', fontsize=20)
plt.ylabel('Accuracy Rate', fontsize=20)
plt.show()
#'''
'''
label = ['DBN (RBM0)', 'DBN (RBM1)', 'DBN (RBM2)', 'SSDBN (RBM0)', 'SSDBN (RBM1)', 'SSDBN (RBM2)']
plt.plot(range(0, 100, 1), error_DBN[0:100:1], color='r')
plt.plot(range(0, 100, 1), error_DBN[100:200:1], color='r', marker='x')
plt.plot(range(0, 100, 1), error_DBN[200:300:1], color='r', marker='|')
plt.plot(range(0, 100, 1), error_SSDBN[0:100:1], color='k')
plt.plot(range(0, 100, 1), error_SSDBN[100:200:1], color='k', marker='x')
plt.plot(range(0, 100, 1), error_SSDBN[200:300:1], color='k', marker='|')
plt.legend(label)
leg = plt.gca().get_legend()
ltext = leg.get_texts()
plt.setp(ltext, fontsize=20)
plt.xlabel('Epoch', fontsize=20)
plt.ylabel('Error', fontsize=20)
plt.show()
'''